name: Update Master Action List

on:
    schedule:
        - cron: '0 14 * * *' # Run everyday at 9am EST
        - cron: '0 18 * * *' # Run everyday at 1pm EST
        - cron: '0 22 * * *' # Run everyday at 5pm EST
    workflow_dispatch:

jobs:
    update-master-list:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository 
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.13

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run scripts
              env: 
                NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
                KANBAN_DB_ID: ${{ secrets.KANBAN_DB_ID }}
                ACTION_ITEMS_DB_ID: ${{ secrets.ACTION_ITEMS_DB_ID }}
              run: python3 main.py
